# Generated by Django 4.1.1 on 2022-09-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='중앙대 310관 1층', max_length=30)),
                ('locker_pw', models.CharField(default='1234', max_length=10)),
                ('locker_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='상품 이름')),
                ('category', models.CharField(choices=[('IT', 'it'), ('BOOK', 'book'), ('DRESS', 'dress'), ('GIFTCARD', 'giftcard')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('start_price', models.IntegerField()),
                ('buyout_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('product_status', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
